/**
 * CIB Analyzer — Credit Memo Export (SheetJS / xlsx-js-style)
 * =============================================================
 * Single-subject summary document for credit approvers.
 * Produces a formatted Excel with key decision-support data.
 */

import {
  APP_NAME, APP_VERSION, TAKA_SYMBOL,
  HEADER_BG_COLOR, HEADER_FONT_COLOR, TITLE_BG_COLOR, TITLE_FONT_COLOR,
  AMOUNT_FORMAT,
} from '../config.js';

// ─────────────────────────── Helpers ──────────────────────────────

function downloadBlob(data, filename, mimeType) {
  const blob = new Blob([data], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─────────────────────────── Styles ──────────────────────────────

const _HEADER_FONT = { name: 'Arial', bold: true, color: { rgb: HEADER_FONT_COLOR }, sz: 10 };
const _HEADER_FILL = { patternType: 'solid', fgColor: { rgb: HEADER_BG_COLOR } };
const _TITLE_FONT = { name: 'Arial', bold: true, color: { rgb: TITLE_FONT_COLOR }, sz: 14 };
const _TITLE_FILL = { patternType: 'solid', fgColor: { rgb: TITLE_BG_COLOR } };
const _BOLD = { name: 'Arial', bold: true, sz: 10 };
const _NORMAL = { name: 'Arial', sz: 10 };
const _BORDER = {
  top:    { style: 'thin' },
  bottom: { style: 'thin' },
  left:   { style: 'thin' },
  right:  { style: 'thin' },
};
const _ALERT_FILL = { patternType: 'solid', fgColor: { rgb: 'FFE0E0' } };
const _GREEN_FILL = { patternType: 'solid', fgColor: { rgb: 'E2EFDA' } };

// ─────────────────────────── Cell Utilities ──────────────────────

function cellRef(r, c) {
  return XLSX.utils.encode_cell({ r, c });
}

function setCell(ws, r, c, value, style) {
  const ref = cellRef(r, c);
  ws[ref] = { v: value, t: typeof value === 'number' ? 'n' : 's', s: style || {} };
  const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');
  if (r > range.e.r) range.e.r = r;
  if (c > range.e.c) range.e.c = c;
  ws['!ref'] = XLSX.utils.encode_range(range);
}

function initSheet() {
  const ws = {};
  ws['!ref'] = 'A1';
  ws['!merges'] = [];
  ws['!cols'] = [];
  return ws;
}

function sectionHeader(ws, row, text) {
  setCell(ws, row, 0, text, {
    font: { name: 'Arial', bold: true, sz: 11, color: { rgb: '1F3864' } },
    fill: { patternType: 'solid', fgColor: { rgb: 'D6E4F0' } },
    border: _BORDER,
  });
  ws['!merges'].push({ s: { r: row, c: 0 }, e: { r: row, c: 5 } });
}

// ─────────────────────────── Main Export ─────────────────────────

/**
 * Generate a credit memo Excel file for a single subject.
 *
 * @param {Object} subjectData - full subject data (from db.get_subject_full)
 * @param {Object} db - database adapter (unused here, kept for API consistency)
 * @param {string} [filename] - optional download filename
 * @returns {Uint8Array} xlsx binary data
 */
export function exportCreditMemo(subjectData, db, filename) {
  const data = subjectData;
  if (!data) throw new Error('No subject data provided');

  const wb = XLSX.utils.book_new();
  const ws = initSheet();

  let row = 0;

  // ── Title ──
  ws['!merges'].push({ s: { r: row, c: 0 }, e: { r: row, c: 5 } });
  setCell(ws, row, 0, 'CREDIT INFORMATION MEMO', {
    font: _TITLE_FONT,
    fill: _TITLE_FILL,
    alignment: { horizontal: 'center' },
  });
  row++;

  const now = new Date();
  const dateStr = `${String(now.getDate()).padStart(2, '0')}/${String(now.getMonth() + 1).padStart(2, '0')}/${now.getFullYear()} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
  ws['!merges'].push({ s: { r: row, c: 0 }, e: { r: row, c: 5 } });
  setCell(ws, row, 0, `Generated by ${APP_NAME} v${APP_VERSION} on ${dateStr}`, {
    font: { sz: 9, italic: true },
  });
  row += 2;

  // ── Subject Details ──
  sectionHeader(ws, row, 'SUBJECT DETAILS');
  row++;

  const name = data.name || data.trade_name || 'Unknown';
  const fields = [
    ['Name', name],
    ['CIB Subject Code', data.cib_subject_code || ''],
    ['Subject Type', data.subject_type || ''],
    ['NID (17)', data.nid_17 || ''],
    ['Match Status', data.match_status || ''],
    ['Risk Rating', data.risk_rating || ''],
  ];

  for (const [label, value] of fields) {
    setCell(ws, row, 0, label, { font: _BOLD, border: _BORDER });
    const valStyle = { font: _NORMAL, border: _BORDER };
    if (label === 'Risk Rating' && (value === 'ADVERSE' || value === 'HIGH RISK')) {
      valStyle.fill = _ALERT_FILL;
    } else if (label === 'Risk Rating' && value === 'LOW RISK') {
      valStyle.fill = _GREEN_FILL;
    }
    setCell(ws, row, 1, String(value), valStyle);
    row++;
  }
  row++;

  // ── Facility Summary ──
  const snapshots = data.summary_snapshots || [];
  if (snapshots.length) {
    sectionHeader(ws, row, 'FACILITY SUMMARY');
    row++;

    const headers = ['Role', 'Living Contracts', 'Outstanding', 'Overdue', 'Stay Order', 'Worst Class.'];
    for (let ci = 0; ci < headers.length; ci++) {
      setCell(ws, row, ci, headers[ci], {
        font: _HEADER_FONT,
        fill: _HEADER_FILL,
        border: _BORDER,
      });
    }
    row++;

    for (const ss of snapshots) {
      const vals = [
        ss.role || '',
        ss.bb_living_contracts || 0,
        ss.bb_total_outstanding || 0,
        ss.bb_total_overdue || 0,
        ss.bb_stay_order_contracts || 0,
        ss.bb_worst_classification || '',
      ];
      for (let ci = 0; ci < vals.length; ci++) {
        const cellStyle = { font: _NORMAL, border: _BORDER };
        if (ci === 2 || ci === 3) cellStyle.numFmt = AMOUNT_FORMAT;
        setCell(ws, row, ci, vals[ci], cellStyle);
      }
      row++;
    }
    row++;
  }

  // ── Alert Flags ──
  const alerts = data.alert_flags || [];
  if (alerts.length) {
    sectionHeader(ws, row, 'ALERT FLAGS');
    row++;

    const headers = ['Severity', 'Flag Type', 'Details', 'Related Contract'];
    for (let ci = 0; ci < headers.length; ci++) {
      setCell(ws, row, ci, headers[ci], {
        font: _HEADER_FONT,
        fill: _HEADER_FILL,
        border: _BORDER,
      });
    }
    row++;

    for (const alert of alerts) {
      const vals = [
        alert.severity || '',
        alert.flag_type || '',
        alert.details || '',
        alert.related_contract || '',
      ];
      for (let ci = 0; ci < vals.length; ci++) {
        const cellStyle = { font: _NORMAL, border: _BORDER };
        if (alert.severity === 'CRITICAL' || alert.severity === 'HIGH') {
          cellStyle.fill = _ALERT_FILL;
        }
        setCell(ws, row, ci, vals[ci], cellStyle);
      }
      row++;
    }
    row++;
  }

  // ── Contract Summary ──
  const contracts = data.contracts || [];
  if (contracts.length) {
    sectionHeader(ws, row, 'CONTRACT SUMMARY');
    row++;

    const headers = ['Contract Code', 'Role', 'Phase', 'Type', 'Sanction Limit', 'Risk'];
    for (let ci = 0; ci < headers.length; ci++) {
      setCell(ws, row, ci, headers[ci], {
        font: _HEADER_FONT,
        fill: _HEADER_FILL,
        border: _BORDER,
      });
    }
    row++;

    for (const c of contracts) {
      const vals = [
        c.cib_contract_code || '',
        c.role || '',
        c.phase || '',
        c.facility_type || '',
        c.sanction_limit || 0,
        c.contract_risk || '',
      ];
      for (let ci = 0; ci < vals.length; ci++) {
        const cellStyle = { font: _NORMAL, border: _BORDER };
        if (ci === 4) cellStyle.numFmt = AMOUNT_FORMAT;
        if (ci === 5 && (vals[ci] === 'ADVERSE' || vals[ci] === 'HIGH')) {
          cellStyle.fill = _ALERT_FILL;
        }
        setCell(ws, row, ci, vals[ci], cellStyle);
      }
      row++;
    }
  }

  // ── Risk Factors ──
  let riskFactors = data.risk_factors || '[]';
  let factors = [];
  try {
    factors = typeof riskFactors === 'string' ? JSON.parse(riskFactors) : riskFactors;
  } catch (_) {
    factors = [];
  }

  if (factors && factors.length) {
    row++;
    sectionHeader(ws, row, 'RISK ASSESSMENT FACTORS');
    row++;
    for (const f of factors) {
      setCell(ws, row, 0, `\u2022 ${f}`, { font: _NORMAL });
      row++;
    }
  }

  // Auto-width: set all 6 columns to 20
  ws['!cols'] = Array(6).fill({ wch: 20 });

  XLSX.utils.book_append_sheet(wb, ws, 'Credit Memo');

  const xlsxData = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });

  if (filename !== undefined) {
    const fname = filename || `CreditMemo_${data.cib_subject_code || 'unknown'}.xlsx`;
    downloadBlob(xlsxData, fname, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  }

  return xlsxData;
}

export { downloadBlob };
